### ISSUE TITLE
When accesing http://localhost/app_dev.php i got a 502 Nginx Bad Gateway

### ISSUE THREAD

**Issue by richhl** [vincentchalamon/docker#5]
Diagnose

Too much information in the header that nginx don't like. See http://blog.mdnsolutions.com/nginx-overwrites-symfony-errors-with-502-bad-gateway/

Solution Add this block to /etc/nginx/sites-enabled/default and restart nginx

```
location ~ ^/(app_dev|config)\.php(/|$) {
...
fastcgi_buffer_size 128k;
fastcgi_buffers 4 256k;
fastcgi_busy_buffers_size 256k;
...
```

gonna make a PR for this

**Comment by SumitGarg007** [comment]
> 

> 

> 

> 

> 

> ### [`**__**`](

- [ ] 

- @ #url

)
Duplicate of #
